WIDTH = 400
HEIGHT = 800
SAMPLE_RATE = 16000
INPUT_SAMPLE_RATE = 16000
ENERGY_THRESHOLD = 3000
RECORD_TIMEOUT = 3

HOME_ROUTE = "/"
RECORD_ROUTE = "/record"
FILE_UPLOAD = "/file_upload"


MODEL_WHISPER = 'assets\\small_convert.bin'